### PR TITLE
news: add osbuild-14 release announcement

### PR DESCRIPTION
**Pull request by dvdhrm**
We forgot to announce osbuild-14 last week. Do this now! Include some
information on the early release date and how we intend to continue.

### CODE REVIEW

**Review by ondrejbudai — APPROVED** [review]

**Comment by ondrejbudai** [comment]
Hmm, now I wonder if the formatting is alright with all those indented bullet points. Have you tried building the posts, @dvdhrm?

**Comment by larskarlitski** [comment]
> Hmm, now I wonder if the formatting is alright with all those indented bullet points. Have you tried building the posts, @dvdhrm?

Yeah, that will look weird. I've always moved the bullets to the left and reformatted the paragraphs.

**Comment by dvdhrm** [comment]
It matches the formatting we have in `NEWS.md`. Both are markdown files.

I don't mind using something else on the website, but maybe we can use the same formatting for both? So far, I liked that `NEWS.md` ended up being formatted as `blockquote`, and thus it looks more like a classic changelog, than like prose. But I am also fine with removing the indentation.

Note that the formatting of the PR as it is looks perfectly fine. It basically emits it as `<pre>`, and since the original is already limited to 80ch, it looks fine. But it is kinda imcompatible with screen-readers and other stuff, which will trip over.

Meh. Anybody willing to make a decision here? Should I just fix NEWS.md everywhere so it is aligned?

**Comment by larskarlitski** [comment]
I prefer it as non-preformatted text, which is why I did that the last rounds. Don't have a strong opinion either way, though.

**Comment by dvdhrm** [comment]
> I prefer it as non-preformatted text, which is why I did that the last rounds. Don't have a strong opinion either way, though.

But... Noooooooooo! I need someone to tell me to go fix all `NEWS.md` to look nice. If nobody tells me to, I have no excuse why I did it!?!?

(btw., I force-pushed a fixed announcement)

**Review by larskarlitski — APPROVED** [review]
Thanks! Sorry for making it all difficult. Wasn't my intention.

**Pull request merged**
